const restaurantsActionsConstants = {
  LOAD_RESTAURANTS_ACTION: "LOAD_RESTAURANTS_ACTION",
  LOAD_RESTAURANTS_SUCCESS_ACTION: "LOAD_RESTAURANTS_SUCCESS_ACTION",
  MAKE_RESTAURANT_ACTION: "MAKE_RESTAURANT_ACTION",
  MAKE_RESTAURANT_SUCCESS_ACTION: "MAKE_RESTAURANT_SUCCESS_ACTION",
  WRITE_REVIEW_ACTION: "WRITE_REVIEW_ACTION",
  WRITE_REVIEW_SUCCESS_ACTION: "WRITE_REVIEW_SUCCESS_ACTION",
  FIND_RESTAURANT_ACTION: "FIND_RESTAURANT_ACTION",
  FIND_RESTAURANT_SUCCESS_ACTION: "FIND_RESTAURANT_SUCCESS_ACTION",
  LOAD_REVIEWS_RESTAURANT_ACTION: "LOAD_REVIEWS_RESTAURANT_ACTION",
  LOAD_REVIEWS_RESTAURANT_SUCCESS_ACTION: "LOAD_REVIEWS_RESTAURANT_SUCCESS_ACTION"
};

export { restaurantsActionsConstants };
