const usersActionsConstants = {
  GET_USER_ACTION: "GET_USER_ACTION",
  GET_USER_SUCCESS_ACTION: "GET_USER_SUCCESS_ACTION",
  CHECK_USERNAME_AVAILABLE_ACTION: "CHECK_USERNAME_AVAILABLE_ACTION",
  CHECK_USERNAME_AVAILABLE_SUCCESS_ACTION: "CHECK_USERNAME_AVAILABLE_SUCCESS_ACTION",
  LOAD_USERS_ACTION: "LOAD_USERS_ACTION",
  LOAD_USERS_SUCCESS_ACTION: "LOAD_USERS_SUCCESS_ACTION",
  REGISTER_USER_ACTION: "REGISTER_USER_ACTION",
  REGISTER_USER_SUCCESS_ACTION: "REGISTER_USER_SUCCESS_ACTION",
  LOGIN_USER_ACTION: "LOGIN_USER_ACTION",
  LOGIN_USER_SUCCESS_ACTION: "LOGIN_USER_SUCCESS_ACTION",
  CHECK_SESSION_ACTION: "CHECK_SESSION_ACTION",
  CHECK_SESSION_SUCCESS_ACTION: "CHECK_SESSION_ACTION",
  LOGOUT_USER_ACTION: "LOGOUT_USER_ACTION",
  LOGOUT_USER_SUCCESS_ACTION: "LOGOUT_USER_SUCCESS_ACTION",
  USER_REVIEWS_ACTION: "USER_REVIEWS_ACTION",
  USER_REVIEWS_SUCCESS_ACTION: "USER_REVIEWS_SUCCESS_ACTION",
  CHANGE_USER_ACTION: "CHANGE_USER_ACTION",
  CHANGE_USER_SUCCESS_ACTION: "CHANGE_USER_SUCCESS_ACTION"
};

export { usersActionsConstants };